### ISSUE TITLE
Germany-Hannover

### ISSUE THREAD

**Issue by TorstenRobitzki** [CPPUserGroups/Germany-Hamburg#1]
Hallo,
kann mir jemand Instruktionen geben, was zu tun ist, um eurem illustren Club an UG Repos bei zu treten?

Schöne Grüße aus Hannover,
Torsten

**Comment by astro1991** [comment]
Moin Torsten,

ich habe Deine Anfrage mal in unsere Mailingliste gepostet.

Viele Grüße

Andreas

http://www.barchfeld.eu
https://www.xing.com/profile/Andreas_Barchfeld
http://veraenderlichesterne.wordpress.com/

PGP-Fingerprint: 1E72 BFA1 0B12 168B 2DE0  9508 116E F5E9 DD86 77B1

**Comment by TorstenRobitzki** [comment]
Moin Moin,

> Am 18.03.2016 um 05:44 schrieb Andreas Barchfeld notifications@github.com:
> 
> ich habe Deine Anfrage mal in unsere Mailingliste gepostet.

danke, dass hat sich schon erledigt. Es gibt jetzt auch eine „Germany-Hannover“ in der Familie der „CPPUserGroups“.

schönen Dank und bis Dienstag
